name: Run main.py

on:
  workflow_dispatch:  # This allows manual triggering from the GitHub Actions UI

jobs:
  run_script:
    runs-on: ubuntu-latest  # You can change this to other OS if needed

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3  # This checks out the repository so the script can be run

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests  # Install the required libraries

    - name: Run main.py
      run: |
        python main.py  # This runs the Python script

    - name: Commit and push changes (if needed)
      run: |
        git config --global user.name "kellyhaps"
        git config --global user.email "kellyhaps@gmail.com"
        git add StephsOrders.json
        git commit -m "Update orders data"
        git push
